### ISSUE TITLE
flatMap is not a function

### ISSUE THREAD

**Issue by lbt05** [planarnetwork/raptor#5]
I'm new to node and try to run your project.
And failed to run the test.

```
  29) RangeQuery
       does not share bestArrivals or routeScanner:
     TypeError: destinationsWithResults.flatMap is not a function
      at GroupStationDepartAfterQuery.getJourneysFromConnections (src/query/GroupStationDepartAfterQuery.ts:88:52)
      at GroupStationDepartAfterQuery.getJourneys (src/query/GroupStationDepartAfterQuery.ts:49:28)
      at GroupStationDepartAfterQuery.plan (src/query/GroupStationDepartAfterQuery.ts:32:26)
      at RangeQuery.plan (src/query/RangeQuery.ts:40:42)
      at Context.it (test/unit/query/RangeQuery.spec.ts:86:26)
```
I wonder how I can fix this issue.

**Comment by linusnorton** [comment]
Update to node 12, it's now in LTS

**Comment by lbt05** [comment]
Thanks. It works.
